# Generated by Django 2.2.1 on 2019-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRead', '0002_auto_20190929_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
