# Generated by Django 2.2.1 on 2019-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=11, verbose_name='书籍编号')),
                ('goods_name', models.CharField(max_length=32, verbose_name='书籍名称')),
                ('goods_status', models.IntegerField(default=1, verbose_name='书籍状态')),
                ('goods_pro_time', models.DateField(auto_now=True, verbose_name='出版日期')),
                ('goods_author_name', models.CharField(max_length=32, verbose_name='作者名字')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名字')),
                ('goods_title', models.CharField(max_length=32, verbose_name='文章')),
                ('goods_content', models.TextField(verbose_name='内容')),
                ('goods_description', models.TextField(verbose_name='描述')),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
    ]
